# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "PLATFORMS" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"NAME" VARCHAR NOT NULL,"UPDATED_AT" timestamp default now() NOT NULL,"CREATED_AT" timestamp default now() NOT NULL);
create table "PRODUCTS" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"NAME" VARCHAR NOT NULL,"PLATFORM_ID" BIGINT NOT NULL,"VERSION" VARCHAR NOT NULL,"DESCRIPTION" VARCHAR,"URL" VARCHAR NOT NULL,"UPDATED_AT" timestamp default now() NOT NULL,"CREATED_AT" timestamp default now() NOT NULL);

# --- !Downs

drop table "PRODUCTS";
drop table "PLATFORMS";

